GET http://localhost:5071/health
Accept: application/json

###

POST http://localhost:5071/shorten
Content-Type: application/json

{
  "URL": "https://www.google.com"
}

###

GET http://localhost:5071/SpTJrHo
Accept: application/json

###

GET http://localhost:5071/SpTJrHo/clicks
Accept: application/json

###

GET http://localhost:5071/SpTJrHo/blank
Accept: application/json

###

GET http://localhost:5071/notReal
Accept: application/json

###

POST http://localhost:5071/
Content-Type: application/json

{
  "URL": "google"
}

###

POST http://localhost:5071/
Content-Type: application/json

{
  "URL": "1234"
}

###

POST http://localhost:5071/
Content-Type: application/json

{
  "URL": ""
}
